apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:qhubAQCanH1d6V8vGWdr5paQXYEo1lWhRgk8m7eqpeDXQp+q5lfDTw==,iv:BD4d+1ludx02XjgM8J+4tldZh0INfUF0OeDyNd642wg=,tag:0NVGDfH8ZBGLcVQIR5O9fg==,type:str]
sops:
  age:
    - recipient: age1yphzfntf2dzja9c0rcpqqw9fdjclw4kzanzvex62yn77jq9z556qrv7r2q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUE5nQ291eHo5WFExb2wz
        dWxsVVUvUm5zcW5XV21vdHlQSTQvWG9TZWd3Cjl4NThyNkVYWXNBSU0vSHBLenFK
        WHBETjNUSktQMXM0eXF1ejB4dXM1c2cKLS0tIG1QUExUclR2U1N6Zk1Gbm0xejU1
        QjZvQUlZTk41NFdkbHNnQ1Z6by9aU1UKFXS4phTw9ZHcgTlit0auldnf6d6mTc8D
        eHPGGUXCH7ltAvwOjmBzdQqd9ZfZfj4UuLsTg4TirLqFsqNxoTts+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T19:15:58Z"
  mac: ENC[AES256_GCM,data:yCbvH8FBwgYBf6lyrof47NC9O/37XPhemubqmtq5UDiUZUkCJS35b70fS1FvRmU/ug600Tjt6lp9w+KRBWNig2utYoFO1gFlVqQlQ63q3SbWrp1/ovseqByX8sDvpFIXOYv4JF5lICItybk262IETgB2CskqGxGTuxiyBiUad9Y=,iv:w0vtw3iTUSB6kdzWfRFJPwRAhBoJI/I17hDFJYIwqEE=,tag:yMKjZ9zJ0XJ0wFhW8YBZyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
