apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:yJihcdUTNXAbiaCQ,iv:fa51aMgF7Sg5jhTqtvD2jnvKjW6Wt3FMR8w97QuMP78=,tag:lL3yBY4D7uaizJU2cK0Ifw==,type:str]
sops:
  age:
    - recipient: age1yphzfntf2dzja9c0rcpqqw9fdjclw4kzanzvex62yn77jq9z556qrv7r2q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcFBwdUdVQXc2MDc4NWNG
        dGZveklCQVBSNzl2ODQzS2haa3ZVT2tMVTNNCm9Za0JvdzBlejBKaklab3pCN1BY
        VnVtQ1Fkb1UxcWE1Q1JjakFFVjNkeWsKLS0tIDA5QURCcGREQ29McldSTUdSbjZO
        L3AwVlBScURLY2o5NTZ0eFFVY0pWSjQK0or+Dia+SJpSuv+o/pswzskY6D5H4f2x
        QOHer4ijbFUDh0sOW+8j7Q0gJiOHyYSoe5XFWMf2rX05Gek+FVef6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T19:15:58Z"
  mac: ENC[AES256_GCM,data:WjCKgaL6HH5CW3Z0Plnyac5y+0DBv8CsZx2/7f6Cxk3APePMHyz4PGgSA4O7/zqbbhGTfFPZgOCAedVr1U6iYLhDA8K2Zj/16BScfrH4EM5IsTBH+u+21ulHEvzMQs5VFUMMp5sGpa0YNSDwy44tMKZx/pJ+xLLyKfFv3oXAvaI=,iv:YsOGmKEKOdkik34/f9h8/+01/LYov3aEiDgBofjIo40=,tag:VZj0eEEzWXqjAWVSoJtyTg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
