apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:f2YGpKx9LVNINZeT4o9FhIotk9gOwd1CSRXhofVb8wQ=,iv:/l44YGl1692QYY/hGK0iwx1r1M2W798pSpxlJ7i77DA=,tag:aS3zswDU+7j7bnsktyBPFQ==,type:str]
sops:
  age:
    - recipient: age1yphzfntf2dzja9c0rcpqqw9fdjclw4kzanzvex62yn77jq9z556qrv7r2q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5d0JEMGE1UGpkOS83bjdk
        Q280ellHQy9hbVdsaXdjYkdwMWFpYTlrN1UwCjUrUzdkZGxXNG5yZWpWOXBJNWtD
        amFWTEtSTUdoU3ZXUW5BMVNRYzlqR1EKLS0tIDZXR3p0a2cwTkR1VGZhcFZ4cXRI
        Nm9mN1duaGZvLzJ2UHJ4N3Q2MHFYLzQK8dwsg3Zuf40FjECrDPEp2lfnhWDx+w2b
        D//hd7qvKD6a+wLFTzNyOBjdGKFjycfVWcNWkUH8WMAInwQNXtUL8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T19:15:58Z"
  mac: ENC[AES256_GCM,data:/srvTXqHRvQ7CLvBDjYST4BhLbVCyDTWdlRC2abCi4Pf8LKh+hENmxZkRImWIBafRRrxuHLnnrNXjPQlXiw2pL8FJA8/M2if4a+WAPXcnuLFs9UBwKPqBaMRvOeMpud8RpKa3EtjkYftoxTSVT4AmVJ0yciShQbiWqgh0bWXJZs=,iv:Nj3AN8vaPJYtUiRzEOBYPCRO2pLmXcPlqTt17rqGYi8=,tag:DDJ3sKoVh04jq2VrhnKUPg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
