apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:lSyIHM6Iv0ds1oUbQFG5L4rGrf6yZWhAiFJFVHUuiUMdYJoZA3aK5ILBF72IkH3Nv7mbIQojNOlECgPT/+KsT9uWyOA/8+2Gzyw7S9M+Q0quQeB7lTAy+Ilc9BWx3DcjDw/3mFwnO+UbCYpnHJgjM4ZqtHFSejVrjMEswR6EXeqRzIogQuxQVaubcaOzgMkhI+mv/UDNLFFNt8VSX3oQMSBmEF/XHW/ALK6CDwbKoLKtuQgb,iv:vSgyp2FCt9Md452UeRPz/F2ofvejGgZljmejju7IGF4=,tag:28lj3ouuUPuj8kU5tXAMrw==,type:str]
sops:
  age:
    - recipient: age1yphzfntf2dzja9c0rcpqqw9fdjclw4kzanzvex62yn77jq9z556qrv7r2q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbGFpaDdZL3VuRy8yemIx
        VTZXZXJXMjJhOUE4K3hPTTJreUNDR24zc3prClI2Nkg4SmdjRjN6V0MwV0JaTnRE
        VmpPNWJLR29RQU9oRHo5TUJ2cHV5NncKLS0tIHJNVWtPVGVJOG9yaGoyOEFCUEZN
        VE16VGFyOGdqbTJGVTdEaTBudVMvT0kKa/NpMkR6GrEytEO+/Lmq855RB6zrEzKv
        q7pbylj3HqEFD3KG8iIoywz42doHNrsdKRUWXoWMMz3eUZNcfyQunA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T19:15:58Z"
  mac: ENC[AES256_GCM,data:FW9gNk+as74kwn+ucvziUs24z8+IXhd+RtY0eAyNmB8EdqeLEhmp/dEzLiapCEzWIk7ear6y2Gu7lEOM0kdtKbd1LfvJPv6qnfJLzyGWnWLJTAKDVePxwiJ5/sQmhXs94sid843zWBQgZdes3+uVr6Ebw0RMxyiURmRvUjl8SmM=,iv:h97gIVr/i56AfvvI3yYUwJ03fvdmSTfnBuvzMDCS74M=,tag:+mtk+UjZvD9uYM/eeLC00g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
