apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:g1U0JfnstWCwSPLpBWJrWZuZcm/ZJSFavm3e3pXkJc0l7decI4ydkA==,iv:3YtRK5hDcEGjkE5E7jkNhnGawU4cJSqNZ1Hdh1UhfB4=,tag:I0A3Am6A7CmDZi9VymmPGg==,type:str]
sops:
  age:
    - recipient: age1yphzfntf2dzja9c0rcpqqw9fdjclw4kzanzvex62yn77jq9z556qrv7r2q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTFkvRWZvRThrZWllZ0ho
        eUh4OTVoK2pRUWlINU1xcVlEOWd4ZURocHdnCkxzU2FXeTRuV3U2S1JxWDl1bzhQ
        K1pqS0ZtS3kvWjdvMEdWZTRHc3F4V2cKLS0tIGRXdm9PVTRKZ05LQ21VMFBwOXRR
        ZTZ6L1M1UDFtbTdHL3N5VW5JUitOdVEKvz5TlsyNCW4HROh7d2UhXKS+FL2KlxVC
        6fzU7V5JDTP21yzQaTY3ZOuBseHqVfzEjXPKZ7mZZL4cAnxoRqhI5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T19:15:58Z"
  mac: ENC[AES256_GCM,data:RplQnnqYTxzO2alFxchiCxWZ3BYvtQrxOIcwvZH6YmAEANuccFRmHheuzdzShbC8aZvHxpVhObJCyomV9EgmwqYc5av6vA0OZqIOkrCja1pdodhLZV7FtbhRAOp413/IqeHRgrrWoyC7OegLCZNGJ57jrlqQFr0CLy6ArBkw0E8=,iv:lhISafcPZ3Nu5TGTRaohMeJO+9KKcnSmO3ApaOCiUD0=,tag:MJvkvKHvye4v8f9BEFCSZw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
